trigger:
 - master

pool:
  vmImage: 'ubuntu-16.04' # examples of other options: 'macOS-10.13', 'vs2017-win2016'

steps:
- task: DotNetCoreCLI@2
  displayName: Test
  inputs:
    command: test
    projects: '**/*Test/*.csproj'
    arguments: '--configuration Release'

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: build
    projects: '**/API.csproj'
    arguments: '--configuration Release' # Update this to match your need

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectedServiceName: 'Free Trial(8f4e1de8-c5a5-4951-8a11-a4bd40eced16)'
    WebAppKind: 'apiApp'
    WebAppName: 'mmtodo'


