trigger:
 - master

pool:
  vmImage: 'ubuntu-16.04' # examples of other options: 'macOS-10.13', 'vs2017-win2016'

steps:
- task: DotNetCoreCLI@2
  displayName: Test
  inputs:
    command: test
    projects: '**/*Test/*.csproj'
    arguments: '--configuration Release'

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: build
    projects: '**/API.csproj'
    arguments: '--configuration Release' # Update this to match your need

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: false
    arguments: --output $(Build.ArtifactStagingDirectory)
    projects: 'API.csproj'
    workingDirectory: '$(Build.SourcesDirectory)/Server/API'
    zipAfterPublish: true

- task: PublishBuildArtifacts@1
  displayName: Publish Artifacts


