trigger:
 - master

pool:
  vmImage: 'ubuntu-16.04' # examples of other options: 'macOS-10.13', 'vs2017-win2016'

steps:
- task: DotNetCoreCLI@2
  displayName: Test
  inputs:
    command: test
    projects: '**/*Test/*.csproj'
    arguments: '--configuration Release'

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: build
    projects: '**/API.csproj'
    arguments: '--configuration Release' # Update this to match your need

- script: dotnet publish $(Build.SourcesDirectory)/Server/API/API.csproj --output $(Build.ArtifactStagingDirectory)

- task: PublishBuildArtifacts@1


