trigger:
 - master

pool:
  vmImage: 'ubuntu-16.04' # examples of other options: 'macOS-10.13', 'vs2017-win2016'

steps:
- task: CmdLine@2
  displayName: Yarn Install
  inputs:
    script: 'yarn install'
    workingDirectory: '$(Build.SourcesDirectory)/Web'

- task: CmdLine@2
  displayName: Test
  inputs:
    script: 'CI=true npm test'
    workingDirectory: '$(Build.SourcesDirectory)/Web'

