trigger:
 - master

pool:
  vmImage: 'ubuntu-16.04' # examples of other options: 'macOS-10.13', 'vs2017-win2016'

steps:
- script: yarn install

- task: Npm@1
  inputs:
    command: 'custom'
    customCommand: 'run build'